### ISSUE TITLE
Divide modules into their own repo

### ISSUE THREAD

**Issue by BarbzYHOOL** [StygianTheBest/AzerothCore-Content#4]
@StygianTheBest I wonder if you could do this so we can fork them one by one (on the official azerothcore repository) and install them easily. If we can fork them one by one (and give you privileges on each), then they will show up in the module catalogue http://www.azerothcore.org/modules-catalogue/

If i want to install only one of your module, I need to clone the whole repo with all the modules.

In top of that, the commit log is not specific to each module which is a big negative point when sharing or developing it.

Also, if we fork it, we will fork the transmog and other modules that we already installed

PS : I noticed you converted the random enchants from Lua, but damn, that's really too bad because there was already a module doing the same exact thing.

**Comment by StygianTheBest** [comment]
I just have to find the time to do it. If you were so inclined, you could individually upload each of the modules to a new repo and clone from there. It's been months since I've even booted my dev box. 

In regards to the commit log, if you view it on Github it links directly to the files modified, and the latest change is posted next to each module is linked directly to those changes as seen here: https://github.com/StygianTheBest/AzerothCore-Content/tree/master/Modules

Also, the random enchants was ported from Trinity I think, I didn't convert it from LUA.

**Comment by BarbzYHOOL** [comment]
> /*
> # Modifications by StygianTheBest
> - v2017.07.29 - Added module announce, Updated strings
> ---
> * Converted from the original LUA script to a module for Azerothcore(Sunwell) :D
> */

Anyway, I'll try to divide them...

**Comment by StygianTheBest** [comment]
Ha! Looking over the code I can tell you that the conversion was quick and easy. I didn't write 90% of it, just put it into the module framework and changed a few vars here and there.

**Comment by BarbzYHOOL** [comment]
I automated the work and pushed them all to the official repo
Now the organization has been taken down, I suppose they thought I was a bot uploading too many repos at once

**Comment by BarbzYHOOL** [comment]
Anyway, for further support and improvement, I think it will happen on the official AzerothCore repositories. Don't hesitate to ask for full permission on these repositories StygianTheBest, I will look on how to do that (10 times in a row :-( )

PS : I let this issue open for people to be aware of the new repos

**Comment by StygianTheBest** [comment]
Moving forward that's probably a good idea. I don't have time to respond as quickly as those who are working in AC day to day. Add me as an admin and I'll chime in if needed.
